server:
  port: 8080

spring:
  liquibase:
    enabled: true
#    drop-first: true
    default-schema: public
    change-log: classpath:db/changelog_init.xml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        hbm2ddl:
          auto: none

cbr_currency_market_url:  https://cbr.ru/scripts/XML_daily.asp

#logging:
#  level:
#    root: INFO
#    com.example.package: INFO
#  file:
#    name: log/log.log
#    totalSizeCap: 10MB
#    historySize: 20MB
#  appender:
#    console:
#      enabled: false
#    file:
#      enabled: true
#  appenders:
#    file:
#      type: FILE
#      markerFilter:
#        marker: CBR_RESPONSE_ERROR
#        level: INFO
#      encoder:
#        pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{35} - %msg%n"
#      rollingPolicy:
#        type: SizeAndTimeBasedRollingPolicy
#        fileNamePattern: "${logging.file.name}.%d{yyyy-MM-dd}.%i"
#        maxFileSize: 10MB
#        maxHistory: 30